### ISSUE TITLE
[Request] a manually update like in the react version ?

### ISSUE THREAD

**Issue by Tristam2** [WouterFlorijn/vue-stack-grid#19]
Hello !
I'm in the case where i need to manually update the grid.
I've quickly check and it doesn't seem that you've implemented the feature yet and it's not listed in the Future plans section.
Could you implement it ?
Thanks a lot 😉

**Comment by WouterFlorijn** [comment]
Hi @Tristam2. It's not in the readme, but you can add a ref to the `Stack` component and then call `reflow()` on that ref. I believe that's what you're looking for. If not, feel free to re-open this issue!
