### ISSUE TITLE
Use other package replacing vue-images-loaded for SSR

### ISSUE THREAD

**Issue by feedgit** [WouterFlorijn/vue-stack-grid#2]
Can I use other package replacing `vue-images-loaded`? I want another package can support SSR ^^

**Comment by WouterFlorijn** [comment]
Do you know if such a package exists? I didn't look into it that much and just picked the first one I found. If it does and works properly then I can integrate it or you can make a PR for it.

**Comment by feedgit** [comment]
Yes. I will try later. Thank for your package!
