### ISSUE TITLE
Cannot read property 'clientWidth' of undefined"

### ISSUE THREAD

**Issue by dimasxp** [WouterFlorijn/vue-stack-grid#20]
https://github.com/WouterFlorijn/vue-stack-grid/blob/c17971f981f5c47b6452a686307e5e08f25691f6/src/Stack.vue#L51

sometimes I get error " Cannot read property 'clientWidth' of undefined" from stack.vue 
![error](https://imgur.com/AhbJEGI.jpg)

**Comment by horaciosolorio** [comment]
Same issue please help.

**Comment by WouterFlorijn** [comment]
@dimasxp @horaciosolorio I published v1.2.2 of this package with a potential fix. Could you check if upgrading solves the problem? Please reopen if not.
