### ISSUE TITLE
Need to remove listener when component is destroyed

### ISSUE THREAD

**Issue by anodeguy** [WouterFlorijn/vue-stack-grid#4]
You add a resize listener when the component is mounted. But you're not removing it when the component is destroyed. This causes javascript to fire errors if you unmount the component (i.e. switch sections or something in your app). 

The actual error (once the component is destroyed):
`Stack.vue?cbef:48 Uncaught TypeError: Cannot read property 'clientWidth' of undefined`

Adding this to the component should resolve this issue:
`destroyed () {
  window.removeEventListener('resize', this.reflow)
}`

**Comment by WouterFlorijn** [comment]
@anodeguy thanks! I added the fix.
