### ISSUE TITLE
How to Run with NUXT?

### ISSUE THREAD

**Issue by shaharyarrahmad** [WouterFlorijn/vue-stack-grid#6]
How can i run this on nuxt app?

**Comment by WouterFlorijn** [comment]
@shaharyarrahmad it should work the same way as explained in the readme. Are you running into any issues?

**Comment by WouterFlorijn** [comment]
Gonna close this, but please let me know if you have any questions.

**Comment by WouterFlorijn** [comment]
See #11 (probably related)
